import os
import pytest
from backend.src.sandbox import execute_python_in_sandbox

def test_execute_python_in_sandbox():
    # Execute a simple Python script in the sandbox container
    code = (
        "import sys\n"
        "print('Hello from the secure Python sandbox!')\n"
        "print(f'Python version: {sys.version}')\n"
    )
    result = execute_python_in_sandbox(code)
    print("\nSandbox Execution Result:\n", result)
    assert "=== 沙盒代码执行完毕" in result
    assert "Hello from the secure Python sandbox!" in result
    assert "Exit Code: 0" in result

def test_execute_python_in_sandbox_with_file():
    # Test reading and writing in the workspace inside sandbox
    # Write a test file from host to workspace
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    workspace_dir = os.path.join(project_root, "workspace")
    os.makedirs(workspace_dir, exist_ok=True)
    
    input_file = os.path.join(workspace_dir, "sandbox_test_in.txt")
    with open(input_file, "w", encoding="utf-8") as f:
        f.write("Input data for sandbox test.")
        
    code = (
        "import os\n"
        "with open('sandbox_test_in.txt', 'r', encoding='utf-8') as f:\n"
        "    data = f.read()\n"
        "print(f'Read data: {data}')\n"
        "with open('sandbox_test_out.txt', 'w', encoding='utf-8') as f:\n"
        "    f.write(data.upper())\n"
    )
    result = execute_python_in_sandbox(code)
    print("\nSandbox Execution File Result:\n", result)
    assert "Read data: Input data for sandbox test." in result
    assert "Exit Code: 0" in result
    
    # Verify file was generated by sandbox on host workspace
    output_file = os.path.join(workspace_dir, "sandbox_test_out.txt")
    assert os.path.exists(output_file)
    with open(output_file, "r", encoding="utf-8") as f:
        out_content = f.read()
    assert out_content == "INPUT DATA FOR SANDBOX TEST."
    
    # Cleanup
    try:
        os.remove(input_file)
        os.remove(output_file)
    except Exception:
        pass
